"""
Makes comparisons between our ONCvar data and previous studies.

This module has functions that generate the answers to questions 
like "How many of our variables are previously known (a) stars or
(b) variables?",  "How many of our periodic variables are are newly
determined to be periodic?", "How do our periods compare to previously
published periods?".

These functions operate on the output table generated by orion_tablemate.py 
and tablemate_script.py.

"""


# A. How many of our variables are previously known stars?
# B. How many of our variables are previously known variables?
# C. How many of our periodic variables are new period determinations?
# D. How do our periods compare to previously published periods?

# We want to do a couple things. 
# One: for a given subset of literature tables, see how many matches
#   a given source has; and to count how many sources have zero matches. 
#    (In the case of question A, the "given subset" is
#     ALL of the literature tables, plus SIMBAD. For question B, it's
#     tables that identify variables specifically. For question C, it's 
#     tables that identify periodic variables, but since some tables might
#     mix periodic and nonperiodic variables and so I'll need to also access
#     the "period" column contained therein, which requires Two.)
# Two: for input tables, access given columns in those tables corresponding
#   to an input source.

